---
controller_hosts:
 - name: Innovate_host1
   inventory: Innovate Inventory
   variables:
     ansible_connection: local
     ansible_python_interpreter: '{{ ansible_playbook_python }}'
 - name: Innovate_host2
   inventory: Innovate Inventory
...
